version: 2.1

language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed ./udagram-api-feed  #Build the images
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker tag udagram-api-feed ooats/udagram-api-feed:v1 #Tagging
  - docker tag udagram-api-user ooats/udagram-api-user:v1
  - docker tag udagram-frontend ooats/udagram-frontend:v1
  - docker tag udagram-reverseproxy ooats/udagram-reverseproxy:v1
# Tasks to perform after the process is successful. 
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push ooats/udagram-api-feed:v1
  - docker push ooats/udagram-api-user:v1
  - docker push ooats/udagram-frontend:v1
  - docker push ooats/udagram-reverseproxy:v1